food/urls.py
from django.urls import path

from .views import DishDetailView, Index, UserRecieptsView, dislike, like, post_order, show_order, pay,\
    show_sales_report

app_name = 'food'

urlpatterns = [
    path('', Index.as_view(), name='main'),
    path('dishes/', UserRecieptsView.as_view(), name='dishes_list'),
    path('dish/<int:pk>/', DishDetailView.as_view(), name='dish_detail'),
    path('order/', show_order, name='show_order'),
    path('order/postorder', post_order, name='post_order'),
    path('order/pay', pay, name='pay'),
    path('like/<int:pk>/', like, name='like'),
    path('dislike/<int:pk>/', dislike, name='dislike'),
    path('saleseport/', show_sales_report, name='show_sales_report'),

]

food_plan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls', namespace='food')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.urls import path
from .views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout')
]

food/models.py
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


class Dish(models.Model):
    title = models.CharField(
        verbose_name='название',
        max_length=50
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )

    recipe = models.TextField(
        verbose_name='рецепт',
        blank=True,
    )

    image = models.ImageField(
        'картинка',
        upload_to='images',
        blank=True,
    )

    categories = models.ManyToManyField(
        'DishCategory',
        related_name='dishes',
        verbose_name='категория',
        blank=True
    )

    meals = models.ManyToManyField(
        'Meal',
        related_name='dishes',
        verbose_name='приемы пищи',
        blank=True
    )

    class Meta:
        verbose_name = 'блюдо'
        verbose_name_plural = 'блюда'

    def __str__(self):
        return self.title

    def get_user_like(self):
        return self.liked_dishs.all()

    def get_user_dislike(self):
        return self.disliked_dishs.all()


class Subscription(models.Model):
    title = models.CharField(
        verbose_name='название',
        max_length=50
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    duration = models.PositiveSmallIntegerField(
        verbose_name='количество',
        validators=[MinValueValidator(1)],
    )
    price = models.DecimalField(
        'цена',
        max_digits=15,
        decimal_places=2,
        validators=[MinValueValidator(0.01)]
    )

    class Meta:
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'

    def __str__(self):
        return self.title


class Sale(models.Model):
    sum = models.DecimalField(
        'цена',
        max_digits=15,
        decimal_places=2,
        validators=[MinValueValidator(0.01)]
    )
    payed_at = models.DateTimeField(
        verbose_name='дата оплаты',
        db_index=True,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='пользователь',
        on_delete=models.PROTECT,
        related_name='sales',
        null=True,
    )

    class Meta:
        verbose_name = 'продажа'
        verbose_name_plural = 'продажи'


class DishCategory(models.Model):
    title = models.CharField(
        verbose_name='название',
        max_length=50
    )

    class Meta:
        verbose_name = 'категория блюд'
        verbose_name_plural = 'категории блюд'

    def __str__(self):
        return self.title


class Meal(models.Model):
    title = models.CharField(
        verbose_name='название',
        max_length=50
    )

    position = models.PositiveSmallIntegerField(
        verbose_name="Position",
        default=0,
        db_index=True,
    )

    class Meta:
        verbose_name = 'прием пищи'
        verbose_name_plural = 'приемы пищи'
        ordering = ['position']

    def __str__(self):
        return self.title

food/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import Sum
from django.db.models.functions import TruncMonth
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.timezone import localdate, localtime
from django.views import View
from django.views.generic import ListView, DetailView

from food.models import Dish, DishCategory, Meal, Sale, Subscription


class Index(View):
    """Представление главной страницы"""
    template_name = 'food/index.html'

    def get(self, request, *args, **kwargs):
        dishes = Dish.objects.all()[:5]
        context = {
            'title': 'FoodPlan главная',
            'dishes': dishes
        }
        return render(request, self.template_name, context)


class UserRecieptsView(ListView):
    """Представление вывода списка рецептов для пользователя"""
    model = Dish
    paginate_by = 4

    def get_queryset(self):
        allergy_to = self.request.user.allergy_to.all().values_list('id', flat=True)
        disliked_dishes = self.request.user.disliked_dishes.all().values_list('id', flat=True)
        return super().get_queryset().exclude(categories__id__in=allergy_to).exclude(id__in=disliked_dishes)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Меню'
        return context


class DishDetailView(DetailView):
    """Представление просмотра рецепта"""
    model = Dish

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Просмотр рецепта'
        return context

@login_required(login_url='/users/login/')
def like(request, pk):
    dish = Dish.objects.get(pk=pk)
    is_like = False
    like_dishes = request.user.liked_dishes.all()
    if dish in like_dishes:
        is_like = False
        request.user.liked_dishes.remove(dish)
    else:
        is_like = True
        request.user.liked_dishes.add(dish)

    return JsonResponse({
        'is_like': is_like,
    })

@login_required(login_url='/users/login/')
def dislike(request, pk):
    dish = Dish.objects.get(pk=pk)
    is_dislike = False
    dislike_dishes = request.user.disliked_dishes.all()
    if dish in dislike_dishes:
        is_dislike = False
        request.user.disliked_dishes.remove(dish)
    else:
        is_dislike = True
        request.user.disliked_dishes.add(dish)

    return JsonResponse({
        'is_dislike': is_dislike,
    })


def show_order(request):
    if not request.user.is_authenticated:
        return redirect('users:login')

    subscriptions = Subscription.objects.all().order_by('duration')
    sum = subscriptions[0].price if subscriptions.exists() else 0

    context = {
        'dish_categories': DishCategory.objects.all(),
        'subscriptions': subscriptions,
        'meals': Meal.objects.all(),
        'sum': sum,
    }

    return render(request, 'food/order.html', context=context)


def post_order(request):
    allergies_ids = [
        str(dish_category.id) for dish_category in DishCategory.objects.all()
        if request.POST.get(f"allergy_{dish_category.id}")
    ]

    meals_ids = [
        str(meal.id) for meal in Meal.objects.all()
        if request.POST.get(f'meal_{meal.id}')
    ]

    subscription_id = int(request.POST.get("term").split(';')[0])
    sum = Subscription.objects.get(id=subscription_id).price

    context = {
        'allergies': ','.join(allergies_ids),
        'meals': ','.join(meals_ids),
        'subscription': subscription_id,
        'sum': sum,
        'persons_number': request.POST.get('persons_number'),
    }
    return render(request, 'food/payment.html', context=context)


def pay(request):
    user = get_user_model().objects.get(id=request.user.id)

    allergies = request.POST.get('allergies')
    if allergies:
        allergies_ids = [int(id) for id in allergies.split(',')]
        user.allergy_to.set(
            DishCategory.objects.filter(id__in=allergies_ids)
        )
    else:
        user.allergy_to.clear()

    meals = request.POST.get('meals')
    if meals:
        meals_ids = [int(id) for id in meals.split(',')]
        user.meals.set(
            Meal.objects.filter(id__in=meals_ids)
        )
    else:
        user.meals.clear()

    subscription = Subscription.objects.get(
        id=int(request.POST.get('subscription'))
    )
    user.subscription = subscription
    user.persons_number = int(request.POST.get('persons_number'))
    user.subscription_start_at = localdate()
    user.save(
        update_fields=[
            'subscription',
            'persons_number',
            'subscription_start_at'
        ]
    )

    Sale.objects.create(
        sum=subscription.price,
        payed_at=localtime(),
        user=user,
    )

    context = {}
    return render(request, 'food/payment_success.html', context=context)


def show_sales_report(request):
    if not request.user.is_authenticated:
        return redirect('users:login')

    sales = Sale.objects.annotate(
        month=TruncMonth('payed_at')).values('month').annotate(
            sum=Sum('sum')
    ).order_by('month')

    context = {
        'title': 'Продажи',
        'sales': sales,
        'total': Sale.objects.aggregate(Sum('sum'))['sum__sum'],
    }
    return render(request, 'food/sales.html', context=context)

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block title %}
        <title>{{ title|title }}</title>
        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
    {% endblock %}
</head>
<body>
    <header>
        {% block header %}
        <nav class="navbar navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="{% url 'food:main' %}">
                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">
                </a>
                {% if user.is_authenticated %}
                    <span style='margin-left: 500px;'>Добро пожаловать {{user.username}}!</span>
                    <a class='btn shadow-none btn-outline-success foodplan_green foodplan__border_green' href="{% url 'users:profile' %}" style='text-decoration:none; cursor:pointer;'>Личный кабинет</a>
                    <a class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green" href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green" href="{% url 'users:login'%}">Войти</a>
                {% endif %}
            </div>
        </nav>
        {% endblock %}
    </header>
    <main style="margin-top: calc(2rem + 85px);">
        {% block content %}
        {% endblock %}
    </main>
    {% block footer %}
    <footer class="footer py-4 mt-5" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-between mb-2">
            <a href="https://vk.com/devmanorg">
                <img src="{% static 'img/vk.png' %}" height="40" width="auto" alt="">
            </a>
            <div>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Виды меню</b></a>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Блог</b></a>
                <a href="#" class="link-dark mx-1" style="text-decoration: none;"><b>Контакты</b></a>
            </div>
        </div>
        <div class="container">
            <h6 class="link-secondary text-center"><a href="#" class="link-secondary me-2">Политика конфиденциальности</a><a href="#" class="link-secondary">Пользовательское соглашение</a></h6>
            <h6 class="link-secondary text-center">© Devman 2022. All right reserved.</h6>
        </div>
    </footer>
    {% endblock %}
    {% block script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

food/templates/food/dish_detail.html
{% extends 'food/base.html' %}
{% load static %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-4 d-flex justify-content-center">
                    <div class="card foodplan__card_borderless">
                        <img src="{{ object.image.url }}" alt="">
                    </div>
                </div>
                <div class="col-12 col-md-8 d-flex flex-column justify-content-between">
                    <div class="row">
                        <h2>{{ object.title }}</h2>
                        <div class="col-12 col-sm-6 d-flex flex-column justify-content-between">
                            <h6>{{ object.desvription }}</h6>

                        </div>
                        <div class="col-12 col-sm-6">
                            <small class="link-secondary">Ингредиенты:</small>
                            <h6>{{ object.recipe }}</h6>
                            <!-- <ul class="list-group list-group-flush">
                                <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                            </ul>
                            <small class="link-secondary">Общая калорийность: 1000 ккал</small> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

food/templates/food/dish_list.html
{% extends 'food/base.html' %}
{% load static %}

{% block content %}
    <div class="dish_list">
        {% for item in object_list %}
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-4 d-flex justify-content-center">
                            <div class="card foodplan__card_borderless">
                                <img src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'img/dish_default.png' %}{% endif %}" alt="">
                            </div>
                        </div>
                        <div class="col-12 col-md-8 d-flex flex-column justify-content-between">
                            <div class="row">
                                <div class="dish-title">
                                    <h2><a href="{% url 'food:dish_detail' item.pk %}">{{ item.title }}</a></h2>
                                    <div class="like-icons">
                                        <li class="like" style="margin-right: 10px;" id="like-{{ item.id }}" data-id="{{ item.id }}">
                                            <i {% if user in item.get_user_like %}class="fa fa-thumbs-up"{% else %}
                                            class="fa fa-thumbs-o-up"{% endif %} data-id="{{item.id }}"></i>
                                        </li>
                                        <li class="dislike" style="margin-right: 10px;" id="dislike-{{ item.id }}" data-id="{{ item.id }}">
                                            <i {% if user in item.get_user_dislike %}class="fa fa-thumbs-down"{% else %}
                                            class="fa fa-thumbs-o-down"{% endif %} data-id="{{item.id }}"></i>
                                        </li>
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 d-flex flex-column justify-content-between">
                                    <h6>{{ item.description }}</h6>

                                </div>
                                <div class="col-12 col-sm-6">

                                    <small class="link-secondary">Ингредиенты:</small>
                                    <h6>{{ item.recipe }}</h6>
                                    <!-- <ul class="list-group list-group-flush"> -->
                                        <!-- <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                        <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                        <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                        <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li>
                                        <li class="list-group-item disabled"><small>ингредиент (500г.)</small></li> -->
                                    <!-- </ul> -->
                                    <!-- <small class="link-secondary">Общая калорийность: 1000 ккал</small> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        {% endfor %}
        <ul class="pagination pagination_dish">
            <li class="page-item">День </li>
            {% for page in page_obj.paginator.page_range %}
                {% if page <= 5 %}
                    {% if page_obj.number == page %}
                        <li class="page-item active"><a class="page-link" href="{% url 'food:dishes_list' %}?page={{ page }}">{{ page }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{% url 'food:dishes_list' %}?page={{ page }}">{{ page }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="{% static 'js/likes.js' %}"></script>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}

{% block content %}
    <section class="foodplan__head_bg">
        <div class="container">
            <div class="d-flex w-50 py-lg-5 foodplan__head">
                <div class="d-flex flex-column justify-content-start foodplan__head_desc">
                    <h1 class="mb-5"><b>Вдохновляем готовить дома!</b></h1>
                    <h4>Мы планируем домашнее меню.<br>
                        Вы получаете рецепты + список продуктов.<br>
                        Больше не нужно думать, что готовить.</h4>
                    <div class="d-block mt-3">
                        <a class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green" href="{% url 'food:show_order' %}">Хочу попробовать</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container my-5">
            <div class="row d-flex justify-content-center">
                <div class="col-sm-6 col-lg-3">
                    <div class="card mb-1 foodplan__card_borderless">
                        <img src="{% static 'img/circle1.png' %}" class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-title"><b>Меню на неделю</b></h5>
                            <p class="card-text">Итальянская паста, котлеты с пюре или овощное карри - решать вам!
                            Подстраивайте меню под свои желания.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="card mb-1 foodplan__card_borderless">
                        <img src="{% static 'img/circle2.png' %}" class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-title"><b>Удобный список продуктов</b></h5>
                            <p class="card-text">С четким списком вы не возьмете лишнего, будете тратить меньше и сможете чаще покупать лосось и морепродукты.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="card mb-1 foodplan__card_borderless">
                        <img src="{% static 'img/circle3.png' %}" class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-title"><b>Доставка от ВкусВилл</b></h5>
                            <p class="card-text">Заказывайте доставку продуктов по вашему списку в 1 клик. Все ингредиенты попадут в корзину ВкусВилл автоматически.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container my-5">
            <h1 class="text-center my-4"><b>В каждом меню только хиты</b></h1>
            <div class="container w-md-75">
                <div id="carousel1" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        {% for dish in dishes %}
                            {% if forloop.first %}
                            <div class="carousel-item active">
                            {% else %}
                            <div class="carousel-item">
                            {% endif %}
                                <a href="{% url 'food:dish_detail' dish.pk %}">
                                    <img src="{% if dish.image %}{{ dish.image.url }}{% else %}{% static 'img/dish_default.png' %}{% endif %}" class="d-block w-100" alt="...">
                                    <div class="card-img-overlay text-white text-center carousel-item__gradient">
                                        <h5><b>{{ dish.description }}</b></h5>
                                        <h2><b>{{ dish.title }}</b></h2>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev carousel__button_prev" type="button" data-bs-target="#carousel1"
                        data-bs-slide="prev">
                        <span class="foodplan_green" aria-hidden="true">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-left-circle carousel__svg_prev"
                                viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                            </svg>
                        </span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next carousel__button_next" type="button" data-bs-target="#carousel1"
                        data-bs-slide="next">
                        <span class="foodplan_green" aria-hidden="true">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-right-circle carousel__svg_next"
                                viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z" />
                            </svg>
                        </span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>

        </div>
    </section>
    <section>
        <div class="container my-5">
            <div class="container w-md-75 foodplan__mobapp">
                <div class="d-flex w-md-50 flex-column align-items-center justify-content-between foodplan__mobapp_desc">
                    <h1 class="py-5"><b>Пользуйтесь, как вам удобно</b></h1>
                    <h4>Открывайте меню в мобильном приложении, на компьютере, планшете, или распечатывайте на принтере.</h4>
                    <h4>Создавайте свою личную коллекцию избранных рецептов.</h4>
                    <div class="d-block py-5">
                        <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green me-2 mb-2">Загрузите в App
                            Store</button>
                        <button class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green me-2 mb-2">Загрузите в Google
                            Play</button>
                    </div>
                </div>
            </div>

        </div>
    </section>
    <section>
        <div class="container mb-5">
            <div class="row">
                <div class="col-12 col-sm-4">
                    <div class="foodplan__creator pounded-pill" style="height: 300px;"></div>
                    <h5 class="text-center">Марина Амельченко</h5>
                    <h6 class="text-center">Основатель Foodplan</h6>
                </div>
                <div class="col-12 col-sm-8">
                    <h1 class="mb-4">,,</h1>
                    <h4>Каждую неделю мы создаем меню с любовью и заботой. Поэтому нам доверяют более 30 000 семей.</h4>
                    <h4>Начните путешествие в мир новых вкусов с нами.</h4>
                    <h1 style="text-align: end;">,,</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container mb-5">
            <h1 class="mb-3 text-center"><strong>Истории наших пользователей</strong></h1>
            <div class="row">
                <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                    <img src="{% static 'img/IMG_1899.jpg' %}" alt="" class="foodplan__story">
                </div>
                <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                    <img src="{% static 'img/IMG_1900.jpg' %}" alt="" class="foodplan__story">
                </div>
                <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                    <img src="{% static 'img/IMG_1901.jpg' %}" alt="" class="foodplan__story">
                </div>
                <div class="card col-12 col-sm-6 col-lg-3 foodplan__card_borderless">
                    <img src="{% static 'img/IMG_1902.jpg' %}" alt="" class="foodplan__story">
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container mb-5">
            <div class="row d-flex justify-content-center">
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="d-flex flex-row justify-content-between m-1">
                        <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                        <div class="d-flex flex-column align-items-center text-center justify-content-center">
                            <h5>Выпускник Сбербанк 500 Startups</h5>
                            <h5>Moscow</h5>
                        </div>
                        <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                    </div>
                </div>
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="d-flex flex-row justify-content-between m-1">
                        <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                        <div class="d-flex flex-column align-items-center text-center justify-content-center">
                            <h5>Диплом повара Le Cordon Bleu</h5>
                            <h5>London</h5>
                        </div>
                        <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                    </div>
                </div>
                <div class="col-12 col-sm-6 col-lg-4">
                    <div class="d-flex flex-row justify-content-between m-1">
                        <img src="{% static 'img/union-left.svg' %}" alt="" class="logo1">
                        <div class="d-flex flex-column align-items-center text-center justify-content-center">
                            <h5>При поддержке Austrian Angel Investors</h5>
                            <h5>Vienna</h5>
                        </div>
                        <img src="{% static 'img/union-right.svg' %}" alt="" class="logo1">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

food/templates/food/payment_success.html
<!--
    Layout source:
        payment successful
            https://codepen.io/Ghost3/pen/XyVBBv
-->
<!DOCTYPE html>
{% load static %}
<html lang="ru" >
<head>
  <meta charset="UTF-8">
  <title>Оплата прошла!</title>
  <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css'>
  <link rel="stylesheet" href="{% static 'css/payment_success.css' %}">

</head>
<body>

<div class="payment-success">
  <div class="body">
    <h2 class="title">Оплата прошла!</h2>
    <img class="main-img" src="https://res.cloudinary.com/dw1zug8d6/image/upload/v1542777688/group-3_3x.png" alt="">
    <p>Оплата успешно прошла! <br>
Вы можете вернуться на сайт "Food plan".</p>
    <a class="btn btn-primary button" href="{% url 'food:main' %}">Вернутся на сайт "Food plan"</a>
  </div>
</div>


</body>
</html>