food/urls.py
from django.urls import path

from .views import DishDetailView, Index, UserRecieptsView, dislike, like, post_order, show_order, pay,\
    show_sales_report

app_name = 'food'

urlpatterns = [
    path('', Index.as_view(), name='main'),
    path('dishes/', UserRecieptsView.as_view(), name='dishes_list'),
    path('dish/<int:pk>/', DishDetailView.as_view(), name='dish_detail'),
    path('order/', show_order, name='show_order'),
    path('order/postorder', post_order, name='post_order'),
    path('order/pay', pay, name='pay'),
    path('like/<int:pk>/', like, name='like'),
    path('dislike/<int:pk>/', dislike, name='dislike'),
    path('saleseport/', show_sales_report, name='show_sales_report'),

]

food_plan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls', namespace='food')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.urls import path
from .views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout')
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from food.models import Subscription, Dish, DishCategory, Meal


class User(AbstractUser):
    subscription = models.ForeignKey(
        Subscription,
        related_name='users',
        verbose_name='Подписка',
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    subscription_start_at = models.DateField(
        'Старт подписки',
        blank=True,
        null=True
    )
    liked_dishes = models.ManyToManyField(
        Dish,
        related_name='liked_dishs',
        verbose_name='Лайкнутые блюда',
        blank=True,
    )
    disliked_dishes = models.ManyToManyField(
        Dish,
        related_name='disliked_dishs',
        verbose_name='Дизлайкнутые блюда',
        blank=True,
    )
    avatar = models.ImageField(
        upload_to='users_images',
        blank=True,
    )

    allergy_to = models.ManyToManyField(
        DishCategory,
        related_name='allergics',
        verbose_name='аллергия на',
        blank=True
    )

    meals = models.ManyToManyField(
        Meal,
        related_name='users',
        verbose_name='приемы пищи',
        blank=True
    )

    persons_number = models.PositiveSmallIntegerField(
        verbose_name='количество персон',
        default=1,
    )

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from .models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(
        attrs={'placeholder': 'Введите адрес эл.почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'id': 'username', 'name': 'username'}), required=False)
    email = forms.CharField(widget=forms.EmailInput(), required=False, disabled=True)
    avatar = forms.ImageField(widget=forms.FileInput(), required=False) 
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'password1', 'name': 'password1'}), required=False)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'password2', 'name': 'password2'}), required=False)
    class Meta:
        model = User
        fields = ('username', 'email', 'avatar', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

users/views.py
from .forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from django.urls import reverse
from django.contrib import auth, messages
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('food:main'))
    else:
        form = UserLoginForm()

    context = {
        'form': form
    }

    return render(request, 'users/login.html', context)


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, 'Вы успешно зарегестрировались')
                return HttpResponseRedirect(reverse('users:login'))
            except:
                messages.error(request, 'Пользователь с такими данными уже существует')
    else:
        form = UserRegistrationForm()

    context = {
        'form': form,
    }

    return render(request, 'users/registration.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('food:main'))


@login_required(login_url='users:login')
def profile(request):
    user = request.user
    subscription = user.subscription
    allergy_to = user.allergy_to.all().values_list('title', flat=True)
    context = {
        'user': user,
        'allergy': allergy_to
    }

    if subscription:
        context['subscription'] = subscription.title
        context['subscription_detail'] = subscription.description

    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=user)
        if form.is_valid():
            if request.POST.get('password1') != request.POST.get('password2'):
                messages.error(request, 'Пароли не совпадают!')
            else:
                try:
                    form.save()
                    return HttpResponseRedirect(reverse('users:profile'))
                except:
                    messages.error(request, 'Пользователь с такими данными уже существует')

    else:
        form = UserProfileForm(instance=user)

    context['form'] = form

    return render(request, 'users/lk.html', context=context)

users/templates/users/lk.html
{% extends 'food/base.html' %}
{% load static %}

{% block content %}
<script src="{% static 'js/main.js' %}"></script>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="card col-12 p-3 mb-5 foodplan__shadow">
                        <h4 class="foodplan__backButton">
                            <strong><small><a href="#" class="link-secondary fw-light"></a></small></strong>
                        </h4>
                        <h2 class="text-center"><strong>Личный кабинет</strong></h2>
                        {% if user.is_staff%}
                          <div class="d-block mt-3">
                            <a class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green" href="{% url 'food:show_sales_report' %}">Отчет по продажам</a>
                          </div>
                        {% endif %}
                    </div>

                    <div class="card col-12 col-md-2 p-3 mb-3 d-flex flex-column align-items-center foodplan__shadow">
                        <div class="position-relative">
                            <img src="{% if user.avatar %} {{ user.avatar.url }} {% else %} {% static 'img/default_avatar.png'%} {% endif %}" alt="" width="100" height="100" class="rounded-pill">
                            <span class="badge rounded-circle position-absolute bottom-0 end-0 foodplan__bg_green avatar__plus"><a href="#"
                                    class="link-dark text-decoration-none align-middle">+</a></span>
                        </div>
                        <h3 class="card-title text-center">{{user}}</h3>
                        <div class="d-block">
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Выйти</button>
                        </div>
                    </div>

                    <div class="card col-12 col-md-10 p-3 mb-3 foodplan__shadow">
                            <ul class="nav nav-tabs">
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab1" class="btn shadow-none foodplan__tab-button active" data-bs-toggle="tab" data-bs-target="#data">Персональные данные</button>
                                </li>
                                <li class="nav-item foodplan__tab-item">
                                    <button id="tab2" class="btn shadow-none foodplan__tab-button" data-bs-toggle="tab" data-bs-target="#menu">Моё меню</button>
                                </li>
                                <li class="nav-item foodplan__tab-item <flex-grow-1"></li>
                            </ul>
                            <div class="tab-content mt-2">
                                {% if messages %}
                                <div class='error' id='error'>
                                    <div class='x-mark' style='cursor: pointer;' onCLick='Vanish();'>X</div>
                                    {% for message in messages %}
                                    {{message}}
                                    {% endfor %}
                                </div>
                                {% endif%}

                                {% if form.errors%}
                                    {{form.errors}}
                                {% endif %}
                                <div class="tab-pane fade show active" id="data">
                                    <form action="{% url 'users:profile' %}" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="{{form.username.id_for_label}}" class="form-label">Логин</label>
                                                <small><a href="#" class="link-dark foodplan_green" onCLick='ChangeUsername()'>изменить</a></small>
                                            </div>

                                            {{form.username}}
                                        </div>
                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="{{form.email.id_for_label}}" class="form-label">Email</label>
                                            </div>

                                            {{form.email}}
                                        </div>


                                        <div class="mb-3">
                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="{{form.password1.id_for_label}}" class="form-label">Пароль</label>
                                                <small><a href="#" class="link-dark foodplan_green" onCLick='ChangePassword()'>изменить</a></small>
                                            </div>

                                            {{form.password1}}

                                            <div class="d-flex align-items-center justify-content-between">
                                                <label for="{{form.password2.id_for_label}}" class="form-label">Подтверждение пароля</label>
                                            </div>

                                            {{form.password2}}
                                        </div>
                                        <div class="d-block">
                                            <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Сохранить
                                                изменения</button>
                                        </div>
                                    </form>
                                </div>
                                <div class="tab-pane fade" id="menu">
                                    <div class="row">
                                        <div class="col-2">
                                            <img src="{% static 'img/circle1.png' %}" alt="" class="w-100">
                                        </div>
                                        <div class="col-10 col-md-10">
                                            <div class="row">
                                                <div class="col-12">
                                                    <h2><a href="{% url 'food:dishes_list' %}">{{ subscription }}</a></h2>
                                                </div>
                                                <div class="col-md-12 col-lg-9">
                                                    <h6>{{ subscription_detail }}</h6>
                                                </div>
                                                <div class="col-md-12 col-lg-3 text-muted d-flex flex-column justify-content-between">
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Персоны: </small><small>{{ user.persons_number }}</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Аллергии: </small><small>{% for alergy_item in allergy %}{{ alergy_item }}, {% endfor %}</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Калории: </small><small>1400</small>
                                                    </div>
                                                    <div class="d-flex flex-row justify-content-between">
                                                        <small>Кол-во приёмов пищи: </small><small>4</small>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                    </div>
                </div>
            </div>
        </section>
    </main>

    {% endblock %}
</body>

users/templates/users/login.html
{% extends 'food/base.html' %}
{% load static %}

{% block content %}
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    {% if messages %}
                    <div class='register-success'>
                        {% for message in messages%}
                            <span>{{ message }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}

                    {% if form.errors%}
                        {{form.errors}}
                    {% endif%}
                    <form action="{% url 'users:login' %}" method="POST">
                        {% csrf_token %}
                        
                        <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                        <div class="mb-3">
                            <label for="{{form.username.id_for_label}}" class="form-label">Логин</label>
                           {{form.username}}
                        </div>
                        <div class="mb-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <label for="{{form.password.id_for_label}}" class="form-label">Пароль</label>
                                <small><a href="#" class="link-dark foodplan_green">Забыли пароль?</a></small>
                            </div>
                            {{form.password}}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit"
                                    class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Нет аккаунта? <a href="{% url 'users:register' %}" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
{% endblock %}

users/templates/users/registration.html
{% extends 'food/base.html' %}
{% load static %}

{% block content%}
    <script src='main.js'></script>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    {% if messages %}
                        <div class='error' id='error' onCLick='Vanish()'>
                            <div class='x-mark'>X</div>
                            {% for message in messages %}
                                {{message}}
                            {% endfor %}
                        </div>
                    {% endif%}

                    {% if form.errors%}
                        {{form.errors}}
                    {% endif%}
                    <form action="{% url 'users:register' %}" method="POST">
                        {% csrf_token %}
                        <h1 class="mb-4 text-center"><strong>Регистрация</strong></h1>
                        <div class="mb-3">
                            <label for="{{form.username.id_for_label}}" class="form-label">Логин</label>
                            {{form.username}}
                        </div>
                        <div class="mb-3">
                            <label for="{{form.email.id_for_label}}" class="form-label">Email</label>
                            {{form.email}}
                        </div>
                        <div class="mb-3">
                            <label for="{{form.password1.id_for_label}}" class="form-label">Пароль</label>
                            {{form.password1}}
                        </div>
                        <div class="mb-3">
                            <label for="{{form.password2.id_for_label}}" class="form-label">Подтверждение пароля</label>
                            {{form.password2}}
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit" class="btn  shadow-nonew-100 btn-outline-success foodplan_green foodplan__border_green">Регистрация</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Уже есть аккаунт? <a href="{% url 'users:login' %}" class="link-dark foodplan_green">Войти</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
{% endblock %}